### ISSUE TITLE
Verify Cert Failure

### ISSUE THREAD

**Issue by ZachChristensen28** [ZachChristensen28/TA-opnsense#47]
The "Verify Certificate" checkbox does not function as expected. 

---

I got the paths correctly in now and I am using the default/stock self-signed cert that comes with OPNsense.  The original error message is gone, but now it says:

`Max retries exceeded with url: /api/core/firmware/info (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1106)')))"`

**Turning off "Verify Certificate" does not change that error message.**

---
_Originally posted by @PMJeffery in https://github.com/ZachChristensen28/TA-opnsense/issues/44#issuecomment-853157661_

**Comment by ZachChristensen28** [comment]
This issue will be fixed in the next release. For a quick fix, you can try the following:

open the file `$SPLUNK_HOME/etc/apps/TA-opnsense/bin/input_module_opnsense_system_information.py`

on line 25 you will find `if verify_cert:`

Change this to:

```shell
if verify_cert == "1":
```

If you don't want to change your code, you can also switch to the development branch where the change is implemented.

```shell
git checkout development
```

**Comment by PMJeffery** [comment]
I edited the python script and it is now working!

sourcetype=opnsense:system is now showing up!



*Paul Jeffery – ***@***.***

Sr. Sales Engineer – Virtual Team

*Splunk Inc.* *>* *Making Data Great Again.*

Mobile: 571.969.PAUL(7285)

**NEW*** Have an Idea or Suggestion? IDEA.SPLUNK.COM
<https://ideas.splunk.com/>*

**FREE*** Splunk Webinars
<https://www.splunk.com/en_us/about-us/events.html> *

*Find us on Reddit <https://www.reddit.com/r/Splunk/>!! *



*Washington D.C.*|San Francisco | Cupertino | London | Hong Kong | Seattle
| Plano | Singapore | Munich | Tokyo



This message is intended only for the personal, confidential, and
authorized use of the recipient(s) named above. If you are not that
person, you are not authorized to review, use, copy, forward, distribute or
otherwise disclose the information contained in the message.



*From:* Zach Christensen ***@***.***>
*Sent:* Wednesday, June 2, 2021 14:51
*To:* ZachChristensen28/TA-opnsense ***@***.***>
*Cc:* PMJeffery ***@***.***>; Mention ***@***.***>
*Subject:* Re: [ZachChristensen28/TA-opnsense] Verify Cert Failure (#47)



[ External sender. Exercise caution. ]

This issue will be fixed in the next release. For a quick fix, you can try
the following:

open the file
$SPLUNK_HOME/etc/apps/TA-opnsense/bin/input_module_opnsense_system_information.py

on line 25 you will find if verify_cert:

Change this to:

if verify_cert == "1":

If you don't want to change your code, you can also switch to the
development branch where the change is implemented.

git checkout development

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ZachChristensen28/TA-opnsense/issues/47#issuecomment-853301638>,
or unsubscribe
